version: '3.1'
services:
  shop:
    build: './shop'
    ports:
      - 80:80
    container_name: shop
  server:
    build: './server'
    ports:
      - 8081:8081
    container_name: server
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
       - ./database/mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=shop
    ports:
      - 3306:3306
      - 33060:33060
    container_name: db
    hostname: db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer