version: '3.1'
services:
  shop:
    build: './shop'
    ports:
      - 80:80
  server:
    build: './server'
    ports:
      - 8081:8081
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
       - ./database/mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=shop
    ports:
      - 3306:3306
      - 33060:33060
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080